POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Maicol Kaiser",
  "email": "maicol.teste@graciosa.com",
  "password": "senhaSegura123"
}


POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "maicol.teste@graciosa.com",
  "password": "senhaSegura123"
}
